# Generated by Django 6.0.4 on 2026-04-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_lat', models.FloatField()),
                ('tx_lng', models.FloatField()),
                ('rx_lat', models.FloatField()),
                ('rx_lng', models.FloatField()),
                ('frequency_mhz', models.FloatField()),
                ('tx_power_dbm', models.FloatField()),
                ('tx_gain_dbi', models.FloatField()),
                ('rx_gain_dbi', models.FloatField()),
                ('sensitivity_dbm', models.FloatField(default=-120.0)),
                ('distance_km', models.FloatField()),
                ('fspl_db', models.FloatField()),
                ('rx_power_dbm', models.FloatField()),
                ('link_ok', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
