# Generated by Django 6.0.4 on 2026-04-26 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationresult',
            name='sensitivity_dbm',
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='bw_hz',
            field=models.IntegerField(default=125000),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='sf',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
