# Generated by Django 6.0.4 on 2026-04-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_remove_simulationresult_sensitivity_dbm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='fresnel_status',
            field=models.CharField(default='OK', max_length=50),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='obstruction_loss_db',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='rx_cable_loss',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='tx_cable_loss',
            field=models.FloatField(default=0.0),
        ),
    ]
