# Generated by Django 6.0.4 on 2026-04-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_simulationresult_fresnel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='environment',
            field=models.CharField(default='Rural', max_length=50),
        ),
    ]
